apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: swagger4-ingress
  labels:
    app: swagger4
    backstage.io/kubernetes-id: swagger4 
spec:
  rules:
    - host: api-swagger4-anderson-dev.empcbr.thoughtworks-labs.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: swagger4
                port: 
                  number: 80
  tls:
  - hosts:
    - api-swagger4-anderson-dev.empcbr.thoughtworks-labs.net
    secretName: letencryptkey
---
apiVersion: v1
kind: Service
metadata:
  name: swagger4
  labels:
    app: swagger4
    backstage.io/kubernetes-id: swagger4
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: swagger4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger4
  labels:
    app: swagger4
    backstage.io/kubernetes-id: swagger4
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  selector:
    matchLabels:
      app: swagger4
  template:
    metadata:
      labels:
        app: swagger4
    spec:
      containers:
      - name: swagger4
        image: 626109959667.dkr.ecr.us-east-1.amazonaws.com/swagger4:{image-tag}
        ports:
        - containerPort: 8080